-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.competitor_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id text NOT NULL,
  user_domain character varying NOT NULL,
  competitor_domain character varying NOT NULL,
  lighthouse_data jsonb,
  pagespeed_data jsonb,
  technical_seo_data jsonb,
  puppeteer_data jsonb,
  backlinks_data jsonb,
  analysis_status character varying DEFAULT 'completed'::character varying,
  error_details text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  google_ads_data jsonb,
  meta_ads_data jsonb,
  instagram_data jsonb,
  facebook_data jsonb,
  traffic_data jsonb,
  content_changes_data jsonb,
  content_updates_data jsonb,
  full_result jsonb,
  CONSTRAINT competitor_cache_pkey PRIMARY KEY (id),
  CONSTRAINT fk_competitor_cache_user FOREIGN KEY (user_id) REFERENCES public.users_table(id)
);
CREATE TABLE public.google_analytics_cache (
  id integer NOT NULL DEFAULT nextval('google_analytics_cache_id_seq'::regclass),
  user_id text NOT NULL UNIQUE,
  property_id text,
  active_users integer DEFAULT 0,
  sessions integer DEFAULT 0,
  bounce_rate numeric DEFAULT 0,
  avg_session_duration numeric DEFAULT 0,
  page_views integer DEFAULT 0,
  conversions integer DEFAULT 0,
  revenue numeric DEFAULT 0,
  total_social_sessions integer DEFAULT 0,
  total_social_users integer DEFAULT 0,
  total_social_conversions integer DEFAULT 0,
  social_conversion_rate numeric DEFAULT 0,
  social_traffic_percentage numeric DEFAULT 0,
  top_social_sources jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_fetched_at timestamp with time zone DEFAULT now(),
  CONSTRAINT google_analytics_cache_pkey PRIMARY KEY (id),
  CONSTRAINT google_analytics_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users_table(id)
);
CREATE TABLE public.lighthouse_cache (
  id integer NOT NULL DEFAULT nextval('lighthouse_cache_id_seq'::regclass),
  user_id text NOT NULL,
  domain text NOT NULL,
  lighthouse_data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_fetched_at timestamp with time zone DEFAULT now(),
  CONSTRAINT lighthouse_cache_pkey PRIMARY KEY (id),
  CONSTRAINT lighthouse_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users_table(id)
);
CREATE TABLE public.oauth_tokens (
  id integer NOT NULL DEFAULT nextval('oauth_tokens_id_seq'::regclass),
  user_email text NOT NULL,
  provider character varying NOT NULL DEFAULT 'google'::text CHECK (provider::text = ANY (ARRAY['google'::character varying, 'facebook'::character varying, 'linkedin'::character varying, 'twitter'::character varying, 'instagram'::character varying]::text[])),
  access_token text NOT NULL,
  refresh_token text,
  expires_at bigint,
  scope text,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  provider_user_id character varying,
  provider_user_name character varying,
  provider_user_email character varying,
  CONSTRAINT oauth_tokens_pkey PRIMARY KEY (id)
);
CREATE TABLE public.se_ranking_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  domain character varying NOT NULL,
  backlinks_data jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT se_ranking_cache_pkey PRIMARY KEY (id),
  CONSTRAINT fk_se_ranking_user FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.search_console_cache (
  id integer NOT NULL DEFAULT nextval('search_console_cache_id_seq'::regclass),
  user_id text NOT NULL UNIQUE,
  site_url text NOT NULL,
  domain text,
  total_clicks integer DEFAULT 0,
  total_impressions integer DEFAULT 0,
  average_ctr numeric DEFAULT 0,
  average_position numeric DEFAULT 0,
  organic_traffic integer DEFAULT 0,
  top_queries jsonb,
  top_pages jsonb,
  daily_data jsonb,
  backlinks jsonb,
  lighthouse jsonb,
  date_range_start date,
  date_range_end date,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_fetched_at timestamp with time zone DEFAULT now(),
  pagespeed_data jsonb,
  technical_seo_data jsonb,
  puppeteer_data jsonb,
  CONSTRAINT search_console_cache_pkey PRIMARY KEY (id),
  CONSTRAINT search_console_cache_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users_table(id)
);
CREATE TABLE public.social_connections (
  id integer NOT NULL DEFAULT nextval('social_connections_id_seq'::regclass),
  email character varying NOT NULL,
  platform character varying NOT NULL CHECK (platform::text = ANY (ARRAY['facebook'::character varying, 'linkedin'::character varying, 'instagram'::character varying, 'twitter'::character varying]::text[])),
  company_url text,
  company_name character varying,
  oauth_connected boolean DEFAULT false,
  created_at timestamp without time zone DEFAULT now(),
  updated_at timestamp without time zone DEFAULT now(),
  CONSTRAINT social_connections_pkey PRIMARY KEY (id)
);
CREATE TABLE public.social_connections_v2 (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_email text NOT NULL,
  platform character varying NOT NULL CHECK (platform::text = ANY (ARRAY['facebook'::character varying, 'instagram'::character varying, 'linkedin'::character varying, 'twitter'::character varying]::text[])),
  is_connected boolean DEFAULT false,
  connection_status character varying DEFAULT 'disconnected'::character varying CHECK (connection_status::text = ANY (ARRAY['connected'::character varying, 'disconnected'::character varying, 'expired'::character varying, 'error'::character varying]::text[])),
  provider_user_id character varying,
  provider_username character varying,
  provider_email character varying,
  account_name character varying,
  profile_url text,
  scopes_granted ARRAY,
  token_expires_at timestamp with time zone,
  last_token_refresh timestamp with time zone,
  platform_metadata jsonb DEFAULT '{}'::jsonb,
  last_error text,
  error_count integer DEFAULT 0,
  last_error_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  connected_at timestamp with time zone,
  disconnected_at timestamp with time zone,
  CONSTRAINT social_connections_v2_pkey PRIMARY KEY (id)
);
CREATE TABLE public.social_media_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_email text NOT NULL,
  platform character varying NOT NULL CHECK (platform::text = ANY (ARRAY['facebook'::character varying, 'instagram'::character varying, 'linkedin'::character varying]::text[])),
  account_id character varying,
  account_name character varying,
  username character varying,
  profile_url text,
  engagement_data jsonb DEFAULT '{}'::jsonb,
  follower_count integer DEFAULT 0,
  follower_growth jsonb DEFAULT '[]'::jsonb,
  top_posts jsonb DEFAULT '[]'::jsonb,
  reputation_data jsonb DEFAULT '{}'::jsonb,
  period character varying DEFAULT 'month'::character varying,
  data_available boolean DEFAULT true,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  last_fetched_at timestamp with time zone DEFAULT now(),
  expires_at timestamp with time zone NOT NULL,
  CONSTRAINT social_media_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.social_media_fetch_history (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_email text NOT NULL,
  platform character varying NOT NULL,
  fetch_type character varying NOT NULL,
  fetch_status character varying NOT NULL CHECK (fetch_status::text = ANY (ARRAY['success'::character varying, 'failed'::character varying, 'partial'::character varying, 'cached'::character varying]::text[])),
  duration_ms integer,
  data_size_bytes integer,
  records_fetched integer DEFAULT 0,
  cache_hit boolean DEFAULT false,
  cache_age_minutes integer,
  error_message text,
  error_code character varying,
  fetched_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_media_fetch_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.social_media_rate_limits (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_email text NOT NULL,
  platform character varying NOT NULL,
  endpoint character varying NOT NULL,
  requests_made integer DEFAULT 0,
  requests_limit integer DEFAULT 200,
  window_start timestamp with time zone DEFAULT now(),
  window_end timestamp with time zone,
  window_duration_minutes integer DEFAULT 60,
  is_limited boolean DEFAULT false,
  limit_reset_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT social_media_rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_business_info (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_email text NOT NULL UNIQUE,
  business_name character varying,
  business_domain character varying NOT NULL,
  business_description text,
  business_industry character varying,
  facebook_handle character varying,
  instagram_handle character varying,
  linkedin_handle character varying,
  twitter_handle character varying,
  youtube_handle character varying,
  tiktok_handle character varying,
  competitors jsonb DEFAULT '[]'::jsonb,
  setup_completed boolean DEFAULT false,
  onboarding_step integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT user_business_info_pkey PRIMARY KEY (id),
  CONSTRAINT user_business_info_user_email_fkey FOREIGN KEY (user_email) REFERENCES public.users_table(email)
);
CREATE TABLE public.users_data (
  id text NOT NULL,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  plan text NOT NULL DEFAULT 'free'::text,
  stripe_id text NOT NULL,
  CONSTRAINT users_data_pkey PRIMARY KEY (id)
);
CREATE TABLE public.users_table (
  id text NOT NULL,
  name text NOT NULL,
  email text NOT NULL UNIQUE,
  plan text NOT NULL DEFAULT 'free'::text,
  stripe_id text DEFAULT ''::text,
  CONSTRAINT users_table_pkey PRIMARY KEY (id)
);