import PDFDocument from 'pdfkit';

/**
 * Comprehensive Report Service
 * Generates all-in-one PDF reports combining SEO, Competitor, and Social Media data
 */
class ComprehensiveReportService {
  constructor() {
    this.colors = {
      primary: '#1f2937',
      secondary: '#6b7280',
      accent: '#3b82f6',
      success: '#10b981',
      warning: '#f59e0b',
      danger: '#ef4444',
      blue: '#3b82f6',
      purple: '#8b5cf6',
      pink: '#ec4899',
      green: '#10b981'
    };
  }

  /**
   * Generate comprehensive business report
   */
  async generateComprehensiveReport(data) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margins: { top: 50, bottom: 50, left: 50, right: 50 }
        });

        const chunks = [];
        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        // Generate comprehensive report
        this.addCoverPage(doc, data);
        this.addExecutiveSummary(doc, data);
        this.addSEOSection(doc, data.seo);
        this.addCompetitorSection(doc, data.competitor);
        this.addSocialMediaSection(doc, data.socialMedia);
        this.addRecommendations(doc, data);
        this.addFooter(doc);

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  /**
   * Generate SEO & Website Performance Report
   */
  async generateSEOReport(data) {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({
          size: 'A4',
          margins: { top: 50, bottom: 50, left: 50, right: 50 }
        });

        const chunks = [];
        doc.on('data', chunk => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        this.addSEOCoverPage(doc, data);
        this.addSEOExecutiveSummary(doc, data);
        this.addLighthouseAnalysis(doc, data.lighthouse);
        this.addCoreWebVitals(doc, data.lighthouse);
        this.addTechnicalSEO(doc, data.technicalSEO);
        this.addPageSpeedAnalysis(doc, data.pagespeed);
        this.addSEORecommendations(doc, data);
        this.addFooter(doc);

        doc.end();
      } catch (error) {
        reject(error);
      }
    });
  }

  // Cover Pages
  addCoverPage(doc, data) {
    doc.fontSize(36)
       .fillColor(this.colors.primary)
       .text('COMPREHENSIVE', 50, 150, { align: 'center' });
    
    doc.fontSize(36)
       .fillColor(this.colors.accent)
       .text('BUSINESS REPORT', 50, 195, { align: 'center' });

    doc.fontSize(18)
       .fillColor(this.colors.secondary)
       .text(data.companyName || 'Your Business', 50, 280, { align: 'center' });

    doc.fontSize(12)
       .fillColor(this.colors.secondary)
       .text(`Generated: ${new Date().toLocaleDateString('en-US', { 
         year: 'numeric', 
         month: 'long', 
         day: 'numeric' 
       })}`, 50, 500, { align: 'center' });

    doc.rect(50, 600, 495, 2)
       .fillColor(this.colors.accent)
       .fill();

    doc.fontSize(8)
       .fillColor(this.colors.secondary)
       .text('Generated by CLARYX Analytics Platform', 50, 720, { align: 'center' });

    doc.addPage();
  }

  addSEOCoverPage(doc, data) {
    doc.fontSize(36)
       .fillColor(this.colors.blue)
       .text('SEO & WEBSITE', 50, 150, { align: 'center' });
    
    doc.fontSize(36)
       .fillColor(this.colors.primary)
       .text('PERFORMANCE REPORT', 50, 195, { align: 'center' });

    doc.fontSize(18)
       .fillColor(this.colors.secondary)
       .text(data.domain || 'Your Website', 50, 280, { align: 'center' });

    doc.fontSize(12)
       .fillColor(this.colors.secondary)
       .text(`Analysis Date: ${new Date().toLocaleDateString('en-US', { 
         year: 'numeric', 
         month: 'long', 
         day: 'numeric' 
       })}`, 50, 500, { align: 'center' });

    doc.rect(50, 600, 495, 2)
       .fillColor(this.colors.blue)
       .fill();

    doc.fontSize(8)
       .fillColor(this.colors.secondary)
       .text('Generated by CLARYX SEO Analytics', 50, 720, { align: 'center' });

    doc.addPage();
  }

  // Executive Summaries
  addExecutiveSummary(doc, data) {
    this.addSectionTitle(doc, 'Executive Summary');

    this.addInfoBox(doc, 'Report Overview', [
      `Company: ${data.companyName || 'Your Business'}`,
      `Analysis Date: ${new Date().toLocaleDateString()}`,
      `Report Type: Comprehensive Business Analysis`,
      `Sections: SEO, Competitor Intelligence, Social Media`
    ]);

    // Key Metrics
    doc.fontSize(14)
       .fillColor(this.colors.primary)
       .text('Key Performance Indicators', 50, doc.y + 20);

    const metrics = [
      { label: 'SEO Score', value: data.seo?.overallScore || 0, max: 100, color: this.colors.blue },
      { label: 'Performance Score', value: data.seo?.lighthouse?.categoryScores?.performance || 0, max: 100, color: this.colors.green },
      { label: 'Social Engagement', value: data.socialMedia?.engagementRate || 0, max: 10, color: this.colors.pink },
      { label: 'Competitive Position', value: data.competitor?.score || 0, max: 100, color: this.colors.purple }
    ];

    metrics.forEach((metric, index) => {
      const y = doc.y + 15;
      doc.fontSize(11)
         .fillColor(this.colors.primary)
         .text(metric.label, 70, y);

      doc.fontSize(11)
         .fillColor(metric.color)
         .text(`${metric.value}/${metric.max}`, 250, y);

      // Progress bar
      const barWidth = (metric.value / metric.max) * 200;
      doc.rect(320, y + 2, 200, 8)
         .fillColor('#f0f0f0')
         .fill();
      
      doc.rect(320, y + 2, barWidth, 8)
         .fillColor(metric.color)
         .fill();
    });

    doc.addPage();
  }

  addSEOExecutiveSummary(doc, data) {
    this.addSectionTitle(doc, 'SEO Performance Summary');

    const lighthouse = data.lighthouse;
    if (lighthouse && lighthouse.categoryScores) {
      this.addInfoBox(doc, 'Lighthouse Scores', [
        `Performance: ${lighthouse.categoryScores.performance}/100`,
        `Accessibility: ${lighthouse.categoryScores.accessibility}/100`,
        `Best Practices: ${lighthouse.categoryScores.bestPractices}/100`,
        `SEO: ${lighthouse.categoryScores.seo}/100`
      ]);

      // Overall Assessment
      const avgScore = Math.round(
        (lighthouse.categoryScores.performance + 
         lighthouse.categoryScores.accessibility + 
         lighthouse.categoryScores.bestPractices + 
         lighthouse.categoryScores.seo) / 4
      );

      doc.fontSize(14)
         .fillColor(this.colors.primary)
         .text('Overall Website Health', 50, doc.y + 25);

      doc.fontSize(48)
         .fillColor(this.getScoreColor(avgScore))
         .text(`${avgScore}`, 70, doc.y + 10);

      doc.fontSize(16)
         .fillColor(this.colors.secondary)
         .text('/100', 130, doc.y - 30);

      doc.fontSize(12)
         .fillColor(this.getScoreColor(avgScore))
         .text(this.getScoreLabel(avgScore), 70, doc.y + 5);
    }

    doc.addPage();
  }

  // Section Methods
  addSEOSection(doc, seoData) {
    if (!seoData) return;

    this.addSectionTitle(doc, 'SEO Analysis');
    
    if (seoData.lighthouse) {
      this.addLighthouseAnalysis(doc, seoData.lighthouse);
    }

    if (seoData.technicalSEO) {
      this.addTechnicalSEO(doc, seoData.technicalSEO);
    }

    doc.addPage();
  }

  addCompetitorSection(doc, competitorData) {
    if (!competitorData) return;

    this.addSectionTitle(doc, 'Competitor Intelligence');

    this.addInfoBox(doc, 'Competitive Analysis', [
      `Competitors Analyzed: ${competitorData.count || 0}`,
      `Your Market Position: ${competitorData.position || 'N/A'}`,
      `Key Strengths: ${competitorData.strengths?.join(', ') || 'N/A'}`,
      `Areas for Improvement: ${competitorData.improvements?.join(', ') || 'N/A'}`
    ]);

    doc.addPage();
  }

  addSocialMediaSection(doc, socialData) {
    if (!socialData) return;

    this.addSectionTitle(doc, 'Social Media Performance');

    this.addInfoBox(doc, 'Social Media Overview', [
      `Total Followers: ${this.formatNumber(socialData.totalFollowers || 0)}`,
      `Engagement Rate: ${socialData.engagementRate || 0}%`,
      `Posts This Month: ${socialData.postsCount || 0}`,
      `Average Reach: ${this.formatNumber(socialData.avgReach || 0)}`
    ]);

    doc.addPage();
  }

  addLighthouseAnalysis(doc, lighthouse) {
    if (!lighthouse || !lighthouse.categoryScores) return;

    this.addSectionTitle(doc, 'Lighthouse Performance Analysis');

    const scores = lighthouse.categoryScores;
    const categories = [
      { name: 'Performance', score: scores.performance, color: this.colors.danger },
      { name: 'Accessibility', score: scores.accessibility, color: this.colors.blue },
      { name: 'Best Practices', score: scores.bestPractices, color: this.colors.purple },
      { name: 'SEO', score: scores.seo, color: this.colors.green }
    ];

    categories.forEach((category, index) => {
      const y = doc.y + 15;
      
      doc.fontSize(12)
         .fillColor(this.colors.primary)
         .text(category.name, 70, y);

      doc.fontSize(12)
         .fillColor(this.getScoreColor(category.score))
         .text(`${category.score}/100`, 250, y);

      // Progress bar
      const barWidth = (category.score / 100) * 250;
      doc.rect(320, y + 2, 250, 10)
         .fillColor('#f0f0f0')
         .fill();
      
      doc.rect(320, y + 2, barWidth, 10)
         .fillColor(this.getScoreColor(category.score))
         .fill();
    });

    doc.y += 20;
  }

  addCoreWebVitals(doc, lighthouse) {
    if (!lighthouse || !lighthouse.coreWebVitals) return;

    this.addSectionTitle(doc, 'Core Web Vitals');

    const vitals = lighthouse.coreWebVitals;
    const vitalsList = [
      { name: 'Largest Contentful Paint (LCP)', value: vitals.lcp?.displayValue || 'N/A', rating: vitals.lcp?.rating },
      { name: 'First Input Delay (FID)', value: vitals.fid?.displayValue || 'N/A', rating: vitals.fid?.rating },
      { name: 'Cumulative Layout Shift (CLS)', value: vitals.cls?.displayValue || 'N/A', rating: vitals.cls?.rating },
      { name: 'First Contentful Paint (FCP)', value: vitals.fcp?.displayValue || 'N/A', rating: vitals.fcp?.rating }
    ];

    vitalsList.forEach((vital, index) => {
      const y = doc.y + 12;
      
      doc.fontSize(10)
         .fillColor(this.colors.primary)
         .text(vital.name, 70, y);

      doc.fontSize(10)
         .fillColor(this.getRatingColor(vital.rating))
         .text(vital.value, 350, y);

      doc.fontSize(9)
         .fillColor(this.getRatingColor(vital.rating))
         .text(vital.rating?.toUpperCase() || 'N/A', 450, y);
    });

    doc.y += 20;
  }

  addTechnicalSEO(doc, technicalSEO) {
    if (!technicalSEO) return;

    this.addSectionTitle(doc, 'Technical SEO Analysis');

    this.addInfoBox(doc, 'Technical SEO Score', [
      `Overall Score: ${technicalSEO.overallScore || 0}/100`,
      `Checks Passed: ${technicalSEO.successfulChecks || 0}/${technicalSEO.checkCount || 0}`,
      `Critical Issues: ${technicalSEO.criticalIssues || 0}`,
      `Warnings: ${technicalSEO.warnings || 0}`
    ]);

    doc.y += 10;
  }

  addPageSpeedAnalysis(doc, pagespeed) {
    if (!pagespeed) return;

    this.addSectionTitle(doc, 'Page Speed Analysis');

    this.addInfoBox(doc, 'Page Speed Metrics', [
      `Mobile Score: ${pagespeed.mobile?.score || 0}/100`,
      `Desktop Score: ${pagespeed.desktop?.score || 0}/100`,
      `Load Time: ${pagespeed.loadTime || 'N/A'}`,
      `Page Size: ${pagespeed.pageSize || 'N/A'}`
    ]);

    doc.y += 10;
  }

  addSEORecommendations(doc, data) {
    this.addSectionTitle(doc, 'SEO Recommendations');

    const recommendations = this.generateSEORecommendations(data);

    recommendations.forEach((rec, index) => {
      doc.fontSize(11)
         .fillColor(this.colors.primary)
         .text(`${index + 1}. ${rec.title}`, 70, doc.y + 12);

      doc.fontSize(9)
         .fillColor(this.colors.secondary)
         .text(rec.description, 85, doc.y + 8, { width: 450 });

      doc.fontSize(8)
         .fillColor(this.getPriorityColor(rec.priority))
         .text(`Priority: ${rec.priority} | Impact: ${rec.impact}`, 85, doc.y + 6);
    });
  }

  addRecommendations(doc, data) {
    this.addSectionTitle(doc, 'Strategic Recommendations');

    const recommendations = [
      {
        category: 'SEO Optimization',
        items: [
          'Improve Core Web Vitals scores',
          'Optimize images and resources',
          'Enhance mobile performance'
        ]
      },
      {
        category: 'Competitive Strategy',
        items: [
          'Monitor competitor performance',
          'Identify market opportunities',
          'Strengthen unique value proposition'
        ]
      },
      {
        category: 'Social Media Growth',
        items: [
          'Increase posting frequency',
          'Engage with audience regularly',
          'Analyze top-performing content'
        ]
      }
    ];

    recommendations.forEach((category, index) => {
      doc.fontSize(13)
         .fillColor(this.colors.primary)
         .text(category.category, 70, doc.y + 15);

      category.items.forEach((item, itemIndex) => {
        doc.fontSize(10)
           .fillColor(this.colors.secondary)
           .text(`• ${item}`, 85, doc.y + 10);
      });
    });
  }

  // Helper Methods
  addSectionTitle(doc, title) {
    if (doc.y > 700) {
      doc.addPage();
    }

    doc.fontSize(18)
       .fillColor(this.colors.primary)
       .text(title, 50, doc.y + 25);

    doc.moveTo(50, doc.y + 8)
       .lineTo(300, doc.y + 8)
       .strokeColor(this.colors.accent)
       .lineWidth(2)
       .stroke();

    doc.y += 15;
  }

  addInfoBox(doc, title, items) {
    const boxHeight = items.length * 15 + 30;
    
    doc.rect(50, doc.y + 10, 495, boxHeight)
       .fillColor('#f8f9fa')
       .fill();

    doc.rect(50, doc.y + 10, 495, boxHeight)
       .strokeColor(this.colors.accent)
       .lineWidth(1)
       .stroke();

    doc.fontSize(12)
       .fillColor(this.colors.primary)
       .text(title, 60, doc.y + 20);

    doc.fontSize(10)
       .fillColor(this.colors.secondary);
    
    items.forEach((item, index) => {
      doc.text(`• ${item}`, 70, doc.y + 15);
    });

    doc.y += 20;
  }

  getScoreColor(score) {
    if (score >= 90) return this.colors.success;
    if (score >= 50) return this.colors.warning;
    return this.colors.danger;
  }

  getScoreLabel(score) {
    if (score >= 90) return 'Excellent';
    if (score >= 75) return 'Good';
    if (score >= 50) return 'Needs Improvement';
    return 'Poor';
  }

  getRatingColor(rating) {
    if (rating === 'good') return this.colors.success;
    if (rating === 'needs-improvement') return this.colors.warning;
    return this.colors.danger;
  }

  getPriorityColor(priority) {
    if (priority === 'High') return this.colors.danger;
    if (priority === 'Medium') return this.colors.warning;
    return this.colors.blue;
  }

  formatNumber(num) {
    if (num >= 1000000) return (num / 1000000).toFixed(1) + 'M';
    if (num >= 1000) return (num / 1000).toFixed(1) + 'K';
    return num.toString();
  }

  generateSEORecommendations(data) {
    const recommendations = [];

    if (data.lighthouse?.categoryScores?.performance < 90) {
      recommendations.push({
        title: 'Improve Page Performance',
        description: 'Optimize images, minify CSS/JS, and leverage browser caching to improve load times.',
        priority: 'High',
        impact: 'High'
      });
    }

    if (data.lighthouse?.categoryScores?.accessibility < 90) {
      recommendations.push({
        title: 'Enhance Accessibility',
        description: 'Add alt text to images, improve color contrast, and ensure proper heading structure.',
        priority: 'Medium',
        impact: 'Medium'
      });
    }

    if (data.lighthouse?.categoryScores?.seo < 90) {
      recommendations.push({
        title: 'Optimize SEO Elements',
        description: 'Improve meta descriptions, title tags, and ensure mobile-friendliness.',
        priority: 'High',
        impact: 'High'
      });
    }

    return recommendations.length > 0 ? recommendations : [
      {
        title: 'Maintain Current Performance',
        description: 'Your website is performing well. Continue monitoring and optimizing.',
        priority: 'Low',
        impact: 'Low'
      }
    ];
  }

  addFooter(doc) {
    const pages = doc.bufferedPageRange();
    for (let i = pages.start; i < (pages.start + pages.count); i++) {
      doc.switchToPage(i);
      
      doc.fontSize(8)
         .fillColor(this.colors.secondary)
         .text(`Generated by CLARYX Analytics Platform - Page ${i - pages.start + 1} of ${pages.count}`, 
               50, 750, { align: 'center', width: 495 });
    }
  }
}

export default new ComprehensiveReportService();
